// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChhM9E44t5hpgQS32szdb1ZyNWij9uWkU',
    appId: '1:884277605531:web:b290f0949c8b9455d3c23e',
    messagingSenderId: '884277605531',
    projectId: 'don-de-sang-d72fb',
    authDomain: 'don-de-sang-d72fb.firebaseapp.com',
    storageBucket: 'don-de-sang-d72fb.appspot.com',
    measurementId: 'G-7399VT1W67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi5YdgOFbQ5MNLQy1_nRavZQGFAs6WuIw',
    appId: '1:884277605531:android:6550b4db9804559cd3c23e',
    messagingSenderId: '884277605531',
    projectId: 'don-de-sang-d72fb',
    storageBucket: 'don-de-sang-d72fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQXzKGMxr_Rstmvo7UnTIqLwpkDykrRsA',
    appId: '1:884277605531:ios:3b0893adcb5b83c0d3c23e',
    messagingSenderId: '884277605531',
    projectId: 'don-de-sang-d72fb',
    storageBucket: 'don-de-sang-d72fb.appspot.com',
    iosClientId: '884277605531-ej4vs3nua16lalr4tab9a0j56rdgfgl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDon0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQXzKGMxr_Rstmvo7UnTIqLwpkDykrRsA',
    appId: '1:884277605531:ios:3b0893adcb5b83c0d3c23e',
    messagingSenderId: '884277605531',
    projectId: 'don-de-sang-d72fb',
    storageBucket: 'don-de-sang-d72fb.appspot.com',
    iosClientId: '884277605531-ej4vs3nua16lalr4tab9a0j56rdgfgl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appDon0',
  );
}
